#!/usr/bin/bash

if [[ $# -ne 1 ]]; then
 echo "stderr"
 exit 1
fi


for file in $(cat "$1"); do
 echo "Description for test case $file:"
 desc_file="${file}.desc"
 if [[ -f "$desc_file" ]]; then
  cat "$desc_file"
 else
  echo "$file: No test description"
 fi
done
